
networks:
  spring-db: {}

services:
#  mariadb:
#    image: 'mariadb:latest'
#    environment:
#      - MARIADB_ROOT_PASSWORD=root
#    command: --init-file /data/application/initdb.sql
#    volumes:
#      - ./initdb.sql:/data/application/initdb.sql
#    ports:
#      - "3306:3306"
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
#      interval: 3s
#      retries: 5
#      start_period: 30s
#    networks:
#      - spring-db

  rabbit:
    image: 'rabbitmq:3-management-alpine'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring-db

#  simple:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      mariadb:
#        condition: service_healthy
#    networks:
#      - spring-db
#    environment:
#      spring.datasource.url: "jdbc:mysql://mariadb:3306/springbootdb?createDatabaseIfNotExist=true"

